### ISSUE TITLE
numbers larger than 53-bits lose precision due to double normalization

### ISSUE THREAD

**Issue by 0xricksanchez** [vapier/pcalc#11]
## Observed behavior

![image](https://user-images.githubusercontent.com/17012133/155172061-404a9c32-17d7-4bb0-8a92-4a21786c3371.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/17012133/155172121-778f4114-c9a9-40ef-97f3-312c148323b9.png)

It seems to work with smaller hex numbers just fine (e.g. by removing the large ff prefix on these numbers:

![image](https://user-images.githubusercontent.com/17012133/155172275-9f8e318e-a2a9-4510-94f5-4a88b0663457.png)

**Comment by vapier** [comment]
could you post terminal context as text rather pictures of text ?  doesn't make much sense and is much harder to interact with.

the problem is basically the same as JS -- pcalc uses `double` to store values which only has 53-bits of precision.  any integers above that will be represented inaccurately.  pcalc has always been this way.  both your numbers normalize to the same floating point number which then have a difference of 0.  so in that regard, the behavior is expected.

it'd be easy to switch pcalc to at least `long double` which would never be worse than `double`, but in many cases would get us at least 64-bits of precision when the underlying platform utilizes [80-bit floats](https://en.wikipedia.org/wiki/Extended_precision#x86_extended_precision_format) as popularized by Intel.  that would make things a little less surprising, at least for people using 64-bit math for people hacking on 64-bit values.

that said, it's just putting a tiny bandaid on a gaping wound.  if the platform's `long double` isn't larger, or the user tries using numbers that don't fit in `long double`, the same unexpected behavior occurs.  the only way to really fix this is to switch to an arbitrary precision backend as documented in #3.
